// Generated by scripts/generate-oss-notices.mjs. Do not edit by hand.
package app.fieldwork.android.features.settings

import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.ListItem
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

private data class LicenseNotice(
    val name: String,
    val license: String,
    val url: String,
)

private val licenseNotices = listOf(
    LicenseNotice("Fieldwork", "AGPL-3.0-or-later", "https://github.com/fieldwork-app/fieldwork"),
    LicenseNotice("Fieldwork App Store Distribution Notice", "AGPL-3.0-or-later additional permission", "https://github.com/fieldwork-app/fieldwork/blob/main/NOTICE"),
    LicenseNotice("SwiftTerm", "MIT", "https://github.com/migueldeicaza/SwiftTerm"),
    LicenseNotice("Sentry Cocoa", "MIT", "https://github.com/getsentry/sentry-cocoa"),
    LicenseNotice("AndroidX", "Apache-2.0", "https://developer.android.com/jetpack/androidx"),
    LicenseNotice("Sentry Java and Android SDK", "MIT", "https://github.com/getsentry/sentry-java"),
    LicenseNotice("Firebase Android SDK", "Apache-2.0", "https://github.com/firebase/firebase-android-sdk"),
    LicenseNotice("CameraX", "Apache-2.0", "https://developer.android.com/media/camera/camerax"),
    LicenseNotice("ML Kit Barcode Scanning", "Apache-2.0", "https://developers.google.com/ml-kit/vision/barcode-scanning"),
    LicenseNotice("ConnectBot termlib", "Apache-2.0", "https://github.com/connectbot/termlib"),
    LicenseNotice("iroh", "MIT OR Apache-2.0", "https://github.com/n0-computer/iroh"),
    LicenseNotice("tokio", "MIT", "https://github.com/tokio-rs/tokio"),
    LicenseNotice("UniFFI", "MPL-2.0", "https://mozilla.github.io/uniffi-rs/"),
    LicenseNotice("wezterm-term", "MIT", "https://github.com/wez/wezterm"),
    LicenseNotice("portable-pty", "MIT", "https://github.com/wez/wezterm"),
    LicenseNotice("redb", "MIT OR Apache-2.0", "https://github.com/cberner/redb"),
    LicenseNotice("serde", "MIT OR Apache-2.0", "https://github.com/serde-rs/serde"),
    LicenseNotice("rustls", "Apache-2.0 OR ISC OR MIT", "https://github.com/rustls/rustls"),
)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun OpenSourceLicensesScreen(padding: PaddingValues, onBack: () -> Unit) {
    Scaffold(
        modifier = Modifier.padding(padding),
        topBar = {
            TopAppBar(
                title = { Text("Open Source") },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
            )
        },
    ) { innerPadding ->
        LazyColumn(modifier = Modifier.padding(innerPadding)) {
            item {
                ListItem(
                    headlineContent = { Text("Fieldwork is open source.") },
                    supportingContent = {
                        Text("This screen lists the primary open-source projects used by the Fieldwork mobile apps and shared Rust core.")
                    },
                )
            }
            items(licenseNotices) { notice ->
                ListItem(
                    headlineContent = { Text(notice.name) },
                    supportingContent = { Text("${notice.license}\n${notice.url}") },
                )
            }
        }
    }
}
