// Generated by scripts/generate-oss-notices.mjs. Do not edit by hand.
import SwiftUI

private struct LicenseNotice: Identifiable {
    let name: String
    let license: String
    let url: String

    var id: String { name }
}

private let licenseNotices = [
    LicenseNotice(name: "Shelly", license: "AGPL-3.0-or-later", url: "https://github.com/iamjr15/shelly"),
    LicenseNotice(name: "Shelly App Store Distribution Notice", license: "AGPL-3.0-or-later additional permission", url: "https://github.com/iamjr15/shelly/blob/main/NOTICE"),
    LicenseNotice(name: "SwiftTerm", license: "MIT", url: "https://github.com/migueldeicaza/SwiftTerm"),
    LicenseNotice(name: "AndroidX", license: "Apache-2.0", url: "https://developer.android.com/jetpack/androidx"),
    LicenseNotice(name: "Firebase Android SDK", license: "Apache-2.0", url: "https://github.com/firebase/firebase-android-sdk"),
    LicenseNotice(name: "CameraX", license: "Apache-2.0", url: "https://developer.android.com/media/camera/camerax"),
    LicenseNotice(name: "ML Kit Barcode Scanning", license: "Apache-2.0", url: "https://developers.google.com/ml-kit/vision/barcode-scanning"),
    LicenseNotice(name: "ConnectBot termlib", license: "Apache-2.0", url: "https://github.com/connectbot/termlib"),
    LicenseNotice(name: "iroh", license: "MIT OR Apache-2.0", url: "https://github.com/n0-computer/iroh"),
    LicenseNotice(name: "tokio", license: "MIT", url: "https://github.com/tokio-rs/tokio"),
    LicenseNotice(name: "UniFFI", license: "MPL-2.0", url: "https://mozilla.github.io/uniffi-rs/"),
    LicenseNotice(name: "wezterm-term", license: "MIT", url: "https://github.com/wez/wezterm"),
    LicenseNotice(name: "portable-pty", license: "MIT", url: "https://github.com/wez/wezterm"),
    LicenseNotice(name: "redb", license: "MIT OR Apache-2.0", url: "https://github.com/cberner/redb"),
    LicenseNotice(name: "serde", license: "MIT OR Apache-2.0", url: "https://github.com/serde-rs/serde"),
    LicenseNotice(name: "rustls", license: "Apache-2.0 OR ISC OR MIT", url: "https://github.com/rustls/rustls"),
]

struct OpenSourceLicensesView: View {
    var body: some View {
        List {
            Section {
                Text("Shelly is open source. This screen lists the primary open-source projects used by the Shelly mobile apps and shared Rust core.")
                    .foregroundStyle(.secondary)
            }

            Section("Licenses") {
                ForEach(licenseNotices) { notice in
                    Link(destination: URL(string: notice.url)!) {
                        VStack(alignment: .leading, spacing: 4) {
                            Text(notice.name)
                                .foregroundStyle(.primary)
                            Text(notice.license)
                                .font(.caption)
                                .foregroundStyle(.secondary)
                        }
                    }
                }
            }
        }
        .navigationTitle("Open Source")
    }
}
