#![deny(missing_docs)]
//! UniFFI mobile client surface for native iOS and Android apps.
//!
//! The API exposes pair/list/attach/input/resize/detach, push-token
//! registration/unregistration, and session create/kill. Session creation is
//! shell-only: the daemon ignores any command, working directory, or environment
//! from mobile clients and spawns the user's default shell, so a paired phone can
//! never launch an arbitrary process at create time. The daemon authorizes
//! create/kill by the paired device identity; the relay/transport never weakens
//! that boundary.

use iroh::endpoint::{RecvStream, SendStream, presets};
use iroh::{Endpoint, EndpointAddr, RelayMode, RelayUrl, SecretKey, TransportAddr};
use serde::{Serialize, de::DeserializeOwned};
use shelly_protocol::{
    AgentState as ProtocolAgentState, CONTRACT_VERSION, ClientKind, ClientSize, ClientToServerMsg,
    ErrorCode, PairingTicket, PushPlatform as ProtocolPushPlatform, ServerToClientMsg, SessionId,
    SessionSummary as ProtocolSessionSummary, max_frame_len, normalize_code,
};
use std::net::SocketAddr;
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};
use tokio::io::{AsyncRead, AsyncReadExt, AsyncWrite, AsyncWriteExt};
use tokio::sync::Mutex;
use tokio::time::{Duration, timeout};

const SHELLY_ALPN: &[u8] = b"shelly/1";
#[cfg(target_os = "android")]
const ANDROID_LOG_TAG: &str = "shelly-core";

macro_rules! android_warn {
    ($($arg:tt)*) => {
        #[cfg(target_os = "android")]
        {
            log::warn!($($arg)*);
        }
    };
}

macro_rules! android_error {
    ($($arg:tt)*) => {
        #[cfg(target_os = "android")]
        {
            log::error!($($arg)*);
        }
    };
}

#[derive(Clone, Debug, uniffi::Record)]
/// Configuration used to construct a mobile Shelly client.
pub struct ClientConfig {
    /// User-facing device name shown in the desktop approval prompt.
    pub device_name: String,
    /// Native platform, used to choose the protocol client kind.
    pub platform: MobilePlatform,
    /// Persisted 32-byte iroh secret key; omitted on first launch to generate one.
    pub device_secret_key: Option<Vec<u8>>,
    /// Persisted daemon connection target after successful pairing.
    pub paired_daemon: Option<DaemonConfig>,
    /// Relay control URL used to resolve a typed pairing code to a ticket.
    ///
    /// Injected from the `SHELLY_RELAY_CONTROL_URL` environment value via the
    /// iOS `ShellyRelayControlURL` Info.plist key and the Android
    /// `SHELLY_RELAY_CONTROL_URL` BuildConfig field. Absent when no relay is
    /// hosted, in which case the typed-code path is unavailable but QR still works.
    pub relay_control_url: Option<String>,
}

#[derive(Clone, Copy, Debug, uniffi::Enum)]
/// Native mobile platform using the shared core.
pub enum MobilePlatform {
    /// iOS app.
    Ios,
    /// Android app.
    Android,
}

#[derive(Clone, Copy, Debug, uniffi::Enum)]
/// Push provider for a token registered by the native app.
pub enum PushPlatform {
    /// Apple Push Notification service token.
    Apns,
    /// Firebase Cloud Messaging token.
    Fcm,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, uniffi::Enum)]
/// Agent state enum exported through UniFFI-safe names.
pub enum AgentStateFfi {
    /// No recent activity or pending input.
    Idle,
    /// PTY output or input indicates active work.
    Working,
    /// Claude/Codex is waiting for user input or approval.
    AwaitingInput,
    /// The session exited abnormally.
    Crashed,
}

#[derive(Clone, Debug, uniffi::Record)]
/// Result of successful QR pairing, persisted by the native app.
pub struct DaemonInfo {
    /// Daemon iroh node id.
    pub daemon_node_id: String,
    /// Relay URL advertised by the daemon, when available.
    pub relay_url: Option<String>,
    /// Direct addresses advertised by the daemon.
    pub addrs: Vec<String>,
    /// Mobile device iroh node id generated by this core.
    pub device_node_id: String,
    /// 32-byte mobile iroh secret key to persist in platform secure storage.
    pub device_secret_key: Vec<u8>,
}

#[derive(Clone, Debug, uniffi::Record)]
/// Persisted daemon target needed to reconnect after pairing.
pub struct DaemonConfig {
    /// Paired daemon iroh node id.
    pub daemon_node_id: String,
    /// Relay URL advertised during pairing, when available.
    pub relay_url: Option<String>,
    /// Direct addresses advertised during pairing.
    pub addrs: Vec<String>,
}

#[derive(Clone, Debug, uniffi::Record)]
/// Dashboard summary exported to native session lists.
pub struct SessionSummaryFfi {
    /// Session UUID string.
    pub id: String,
    /// User-facing session label.
    pub name: String,
    /// Command and arguments running on the desktop.
    pub command: Vec<String>,
    /// Desktop working directory as display text.
    pub cwd: String,
    /// UTC creation time in milliseconds since the Unix epoch.
    pub created_at: u64,
    /// UTC last-activity time in milliseconds since the Unix epoch.
    pub last_activity: u64,
    /// Current inferred agent/session state.
    pub state: AgentStateFfi,
    /// Sanitized, truncated terminal preview for dashboard cards.
    pub last_line: Option<String>,
    /// Optional AI model label.
    pub model: Option<String>,
}

#[derive(Debug, thiserror::Error, uniffi::Error)]
#[uniffi(flat_error)]
/// Error type mapped across Swift and Kotlin bindings.
pub enum ShellyError {
    /// Client configuration or caller input is invalid.
    #[error("invalid config: {0}")]
    InvalidConfig(String),
    /// iroh transport or stream IO failed.
    #[error("transport error: {0}")]
    Transport(String),
    /// The daemon returned an unexpected or invalid protocol response.
    #[error("protocol error: {0}")]
    Protocol(String),
    /// The daemon rejected the client identity.
    #[error("unauthorized: {0}")]
    Unauthorized(String),
    /// The client is authenticated but not allowed to perform the operation.
    #[error("forbidden: {0}")]
    Forbidden(String),
    /// The requested session or resource does not exist.
    #[error("not found: {0}")]
    NotFound(String),
    /// Internal daemon or mobile-core error.
    #[error("internal error: {0}")]
    Internal(String),
}

#[uniffi::export(callback_interface)]
/// Callback interface for session-list subscriptions.
pub trait SessionListSink: Send + Sync {
    /// Receives a complete replacement session list.
    fn on_update(&self, sessions: Vec<SessionSummaryFfi>);
}

#[uniffi::export(callback_interface)]
/// Callback interface for attached terminal byte streams.
pub trait ByteStreamSink: Send + Sync {
    /// Receives replay or synthetic snapshot bytes immediately after attach.
    fn on_initial_bytes(&self, bytes: Vec<u8>);
    /// Receives raw PTY output bytes.
    fn on_output(&self, bytes: Vec<u8>);
    /// Receives an inferred agent-state change.
    fn on_agent_state(&self, state: AgentStateFfi);
    /// Receives a subscriber-overflow signal; native UI should reattach/resync.
    ///
    /// The v1 wire field is named `skipped_bytes`, but the value is the number
    /// of daemon broadcast messages skipped by the receiver.
    fn on_lag(&self, skipped_bytes: u64);
    /// Receives the process exit code when the session terminates.
    fn on_session_exited(&self, code: i32);
}

#[derive(uniffi::Object)]
/// Mobile client object that owns the device iroh identity.
pub struct ShellyClient {
    config: ClientConfig,
    secret_key: SecretKey,
    http: reqwest::Client,
    daemon: Mutex<Option<DaemonTarget>>,
    endpoint: Mutex<Option<Endpoint>>,
    connected: Mutex<bool>,
}

#[derive(Clone, Debug)]
struct DaemonTarget {
    node_id: String,
    relay_url: Option<String>,
    addrs: Vec<String>,
}

fn build_http_client() -> Result<reqwest::Client, ShellyError> {
    let root_store =
        rustls::RootCertStore::from_iter(webpki_roots::TLS_SERVER_ROOTS.iter().cloned());
    let mut tls = rustls::ClientConfig::builder_with_provider(Arc::new(
        rustls::crypto::ring::default_provider(),
    ))
    .with_safe_default_protocol_versions()
    .map_err(|error| {
        ShellyError::Internal(format!(
            "failed to configure HTTPS TLS protocol versions: {error}"
        ))
    })?
    .with_root_certificates(root_store)
    .with_no_client_auth();
    tls.alpn_protocols = vec![b"h2".to_vec(), b"http/1.1".to_vec()];

    reqwest::Client::builder()
        .use_preconfigured_tls(tls)
        .build()
        .map_err(|error| ShellyError::Internal(format!("failed to create HTTPS client: {error}")))
}

#[cfg(target_os = "android")]
fn init_android_logging() {
    static INIT: std::sync::Once = std::sync::Once::new();

    INIT.call_once(|| {
        android_logger::init_once(
            android_logger::Config::default()
                .with_max_level(log::LevelFilter::Trace)
                .with_tag(ANDROID_LOG_TAG),
        );

        let previous_hook = std::panic::take_hook();
        std::panic::set_hook(Box::new(move |info| {
            let message = info
                .payload()
                .downcast_ref::<&str>()
                .copied()
                .or_else(|| info.payload().downcast_ref::<String>().map(String::as_str))
                .unwrap_or("non-string panic payload");
            let location = info
                .location()
                .map(|location| {
                    format!(
                        "{}:{}:{}",
                        location.file(),
                        location.line(),
                        location.column()
                    )
                })
                .unwrap_or_else(|| "unknown location".to_string());

            log::error!("panic at {location}: {message}");
            previous_hook(info);
        }));
    });
}

#[cfg(not(target_os = "android"))]
fn init_android_logging() {}

#[uniffi::export(async_runtime = "tokio")]
impl ShellyClient {
    #[uniffi::constructor]
    /// Creates a client, generating a device key when no persisted key is supplied.
    pub fn new(config: ClientConfig) -> Result<Arc<Self>, ShellyError> {
        init_android_logging();
        let secret_key = match &config.device_secret_key {
            Some(bytes) => SecretKey::from_bytes(&bytes.as_slice().try_into().map_err(|_| {
                ShellyError::InvalidConfig(
                    "stored mobile identity key is invalid: expected 32 bytes".to_string(),
                )
            })?),
            None => SecretKey::generate(),
        };

        let daemon = config.paired_daemon.as_ref().map(DaemonTarget::from_config);
        let http = build_http_client()?;

        Ok(Arc::new(Self {
            config,
            secret_key,
            http,
            daemon: Mutex::new(daemon),
            endpoint: Mutex::new(None),
            connected: Mutex::new(false),
        }))
    }

    /// Pairs with a daemon using the compact ticket embedded in the desktop QR.
    ///
    /// The scanned string is a `sh1`-prefixed [`PairingTicket`] carrying both the
    /// daemon's reachability and the short code, so a scan needs no typing.
    pub async fn pair_with_qr(
        self: Arc<Self>,
        qr_payload: String,
    ) -> Result<DaemonInfo, ShellyError> {
        let ticket = PairingTicket::decode(qr_payload.trim()).map_err(|error| {
            ShellyError::Protocol(format!("invalid pairing QR payload: {error}"))
        })?;
        self.pair_with_ticket(ticket).await
    }

    /// Pairs with a daemon using a short typed code resolved through the relay.
    ///
    /// The code is normalized, then exchanged for the daemon's [`PairingTicket`]
    /// via the relay rendezvous endpoint. Requires a configured relay control
    /// URL; the typed-code path is unavailable when no relay is hosted.
    pub async fn pair_with_code(self: Arc<Self>, code: String) -> Result<DaemonInfo, ShellyError> {
        let code = normalize_code(&code);
        let relay_control_url = self
            .config
            .relay_control_url
            .as_deref()
            .ok_or_else(|| {
                ShellyError::InvalidConfig(
                    "typed pairing codes are unavailable because no relay control URL is configured"
                        .to_string(),
                )
            })?
            .trim_end_matches('/');
        let url = format!("{relay_control_url}/v1/pair/resolve/{code}");

        let response = self.http.get(&url).send().await.map_err(|error| {
            let error = error.without_url();
            android_error!("failed to resolve pairing code through relay: {error}");
            ShellyError::Transport(format!(
                "failed to resolve pairing code through the relay: {error}"
            ))
        })?;
        let status = response.status();
        if status == reqwest::StatusCode::NOT_FOUND {
            android_warn!("pairing relay returned HTTP {status} while resolving typed code");
            return Err(ShellyError::NotFound(
                "pairing code not found, expired, or already used".to_string(),
            ));
        }
        if !status.is_success() {
            android_error!("pairing relay returned HTTP {status} while resolving typed code");
            return Err(ShellyError::Protocol(format!(
                "pairing relay returned HTTP {} while resolving the code",
                status
            )));
        }
        let resolved: ResolvePairingResponse = response.json().await.map_err(|error| {
            let error = error.without_url();
            android_error!("pairing relay returned an invalid resolve response: {error}");
            ShellyError::Protocol(format!(
                "pairing relay returned an invalid resolve response: {error}"
            ))
        })?;
        let ticket = PairingTicket::decode(resolved.ticket_blob.trim()).map_err(|error| {
            android_error!("pairing relay returned an invalid pairing ticket: {error}");
            ShellyError::Protocol(format!(
                "pairing relay returned an invalid pairing ticket: {error}"
            ))
        })?;
        self.pair_with_ticket(ticket).await
    }

    /// Connects to a previously paired daemon and verifies authorization with a ping.
    pub async fn connect(self: Arc<Self>) -> Result<(), ShellyError> {
        let target = self.daemon_target().await?;
        let endpoint = self.endpoint(target.parsed_relay()?.as_ref()).await?;
        let (mut send, mut recv) = open_stream(&endpoint, &target).await?;
        write_hello(&mut send, self.config.platform).await?;
        expect_welcome(&mut recv).await?;
        write_msg(&mut send, &ClientToServerMsg::Ping { seq: 1 }).await?;
        match read_msg::<ServerToClientMsg>(&mut recv).await? {
            ServerToClientMsg::Pong { seq: 1 } => {
                *self.connected.lock().await = true;
                Ok(())
            }
            ServerToClientMsg::Error { code, message } => Err(error_from_server(code, message)),
            other => Err(ShellyError::Protocol(format!(
                "unexpected daemon response during connect: {other:?}"
            ))),
        }
    }

    /// Marks the client disconnected locally; active attach streams are closed by their owners.
    pub async fn disconnect(self: Arc<Self>) -> Result<(), ShellyError> {
        *self.connected.lock().await = false;
        Ok(())
    }

    /// Fetches the current session list from the paired daemon.
    pub async fn list_sessions(self: Arc<Self>) -> Result<Vec<SessionSummaryFfi>, ShellyError> {
        let (mut send, mut recv) = self.open_authenticated_stream().await?;
        write_msg(&mut send, &ClientToServerMsg::ListSessions).await?;
        match read_msg::<ServerToClientMsg>(&mut recv).await? {
            ServerToClientMsg::SessionList { sessions } => {
                Ok(sessions.into_iter().map(Into::into).collect())
            }
            ServerToClientMsg::Error { code, message } => Err(error_from_server(code, message)),
            other => Err(ShellyError::Protocol(format!(
                "unexpected daemon response to ListSessions: {other:?}"
            ))),
        }
    }

    /// Creates a new shell session on the paired daemon and returns its summary.
    ///
    /// Mobile create is shell-only: the daemon ignores any command, working
    /// directory, or environment and spawns the user's default shell. The optional
    /// `name` is a label; an empty name asks the daemon to generate a memorable one.
    pub async fn create_session(
        self: Arc<Self>,
        name: Option<String>,
    ) -> Result<SessionSummaryFfi, ShellyError> {
        let (mut send, mut recv) = self.open_authenticated_stream().await?;
        write_msg(
            &mut send,
            &ClientToServerMsg::CreateSession {
                name: name.unwrap_or_default(),
                command: Vec::new(),
                cwd: std::path::PathBuf::from("/"),
                env: std::collections::HashMap::new(),
                size: ClientSize { cols: 80, rows: 24 },
            },
        )
        .await?;
        match read_msg::<ServerToClientMsg>(&mut recv).await? {
            ServerToClientMsg::SessionCreated { summary, .. } => Ok(summary.into()),
            ServerToClientMsg::Error { code, message } => Err(error_from_server(code, message)),
            other => Err(ShellyError::Protocol(format!(
                "unexpected daemon response to CreateSession: {other:?}"
            ))),
        }
    }

    /// Kills a session on the paired daemon.
    ///
    /// Fire-and-forget: the daemon sends no response and treats a missing session
    /// as already killed, so this returns once the request is flushed. The
    /// session-list subscription reflects the removal.
    pub async fn kill_session(self: Arc<Self>, id: String) -> Result<(), ShellyError> {
        let session_id = id
            .parse::<SessionId>()
            .map_err(|error| ShellyError::InvalidConfig(format!("invalid session id: {error}")))?;
        let (mut send, _recv) = self.open_authenticated_stream().await?;
        write_msg(&mut send, &ClientToServerMsg::KillSession { session_id }).await?;
        let _ = send.finish();
        Ok(())
    }

    /// Attaches to a session by id.
    pub async fn attach_session(
        self: Arc<Self>,
        id: String,
    ) -> Result<Arc<AttachedSession>, ShellyError> {
        self.attach_session_from(id, None).await
    }

    /// Attaches to a desktop-created session and asks the daemon to replay from a byte offset.
    pub async fn attach_session_from(
        self: Arc<Self>,
        id: String,
        last_seen_seq: Option<u64>,
    ) -> Result<Arc<AttachedSession>, ShellyError> {
        let session_id = id
            .parse::<SessionId>()
            .map_err(|error| ShellyError::InvalidConfig(format!("invalid session id: {error}")))?;
        let (mut send, mut recv) = self.open_authenticated_stream().await?;
        write_msg(
            &mut send,
            &ClientToServerMsg::AttachSession {
                session_id,
                size: ClientSize { cols: 80, rows: 24 },
                last_seen_seq,
            },
        )
        .await?;
        match read_msg::<ServerToClientMsg>(&mut recv).await? {
            ServerToClientMsg::Attached {
                initial_bytes, seq, ..
            } => Ok(Arc::new(AttachedSession {
                session_id,
                send: Mutex::new(Some(send)),
                recv: Mutex::new(Some(recv)),
                initial_bytes: Mutex::new(Some(initial_bytes)),
                initial_seq: seq,
                last_seen_seq: AtomicU64::new(seq),
            })),
            ServerToClientMsg::Error { code, message } => Err(error_from_server(code, message)),
            other => Err(ShellyError::Protocol(format!(
                "unexpected daemon response to AttachSession: {other:?}"
            ))),
        }
    }

    /// Emits the current session list through a callback.
    pub async fn subscribe_sessions(
        self: Arc<Self>,
        sink: Box<dyn SessionListSink>,
    ) -> Result<(), ShellyError> {
        let (mut send, mut recv) = self.open_authenticated_stream().await?;
        write_msg(&mut send, &ClientToServerMsg::SubscribeSessions).await?;
        loop {
            match read_msg::<ServerToClientMsg>(&mut recv).await? {
                ServerToClientMsg::SessionList { sessions } => {
                    sink.on_update(sessions.into_iter().map(Into::into).collect());
                }
                ServerToClientMsg::Error { code, message } => {
                    return Err(error_from_server(code, message));
                }
                other => {
                    return Err(ShellyError::Protocol(format!(
                        "unexpected daemon response to SubscribeSessions: {other:?}"
                    )));
                }
            }
        }
    }

    /// Registers the native APNs/FCM token with the paired daemon.
    pub async fn register_push_token(
        self: Arc<Self>,
        platform: PushPlatform,
        token: String,
    ) -> Result<(), ShellyError> {
        let (mut send, mut recv) = self.open_authenticated_stream().await?;
        write_msg(
            &mut send,
            &ClientToServerMsg::RegisterPushToken {
                platform: platform.into(),
                token,
            },
        )
        .await?;
        match read_msg::<ServerToClientMsg>(&mut recv).await? {
            ServerToClientMsg::Pong { .. } => Ok(()),
            ServerToClientMsg::Error { code, message } => Err(error_from_server(code, message)),
            other => Err(ShellyError::Protocol(format!(
                "unexpected daemon response to RegisterPushToken: {other:?}"
            ))),
        }
    }

    /// Unregisters the native APNs/FCM token from the paired daemon.
    pub async fn unregister_push_token(
        self: Arc<Self>,
        platform: PushPlatform,
        token: String,
    ) -> Result<(), ShellyError> {
        let (mut send, mut recv) = self.open_authenticated_stream().await?;
        write_msg(
            &mut send,
            &ClientToServerMsg::UnregisterPushToken {
                platform: platform.into(),
                token,
            },
        )
        .await?;
        match read_msg::<ServerToClientMsg>(&mut recv).await? {
            ServerToClientMsg::Pong { .. } => Ok(()),
            ServerToClientMsg::Error { code, message } => Err(error_from_server(code, message)),
            other => Err(ShellyError::Protocol(format!(
                "unexpected daemon response to UnregisterPushToken: {other:?}"
            ))),
        }
    }
}

impl ShellyClient {
    /// Shared dial-and-pair path for both the QR and typed-code flows.
    async fn pair_with_ticket(&self, ticket: PairingTicket) -> Result<DaemonInfo, ShellyError> {
        let target = DaemonTarget::from_ticket(&ticket);
        let endpoint = self.endpoint(target.parsed_relay()?.as_ref()).await?;
        let (mut send, mut recv) = open_stream(&endpoint, &target).await?;

        write_hello(&mut send, self.config.platform).await?;
        expect_welcome(&mut recv).await?;
        write_msg(
            &mut send,
            &ClientToServerMsg::PairWithCode {
                code: ticket.code,
                device_name: self.config.device_name.clone(),
                device_node_id: endpoint.id().to_string(),
            },
        )
        .await?;

        match read_msg::<ServerToClientMsg>(&mut recv).await? {
            ServerToClientMsg::PairingComplete { daemon_node_id } => {
                *self.daemon.lock().await = Some(target.clone());
                *self.connected.lock().await = true;
                Ok(DaemonInfo {
                    daemon_node_id,
                    relay_url: target.relay_url,
                    addrs: target.addrs,
                    device_node_id: endpoint.id().to_string(),
                    device_secret_key: self.secret_key.to_bytes().to_vec(),
                })
            }
            ServerToClientMsg::Error { code, message } => Err(error_from_server(code, message)),
            other => Err(ShellyError::Protocol(format!(
                "unexpected daemon response during pairing: {other:?}"
            ))),
        }
    }

    async fn daemon_target(&self) -> Result<DaemonTarget, ShellyError> {
        self.daemon.lock().await.clone().ok_or_else(|| {
            ShellyError::InvalidConfig(
                "client has no saved daemon pairing; pair this device first".to_string(),
            )
        })
    }

    async fn open_authenticated_stream(&self) -> Result<(SendStream, RecvStream), ShellyError> {
        let target = self.daemon_target().await?;
        let endpoint = self.endpoint(target.parsed_relay()?.as_ref()).await?;
        let (mut send, mut recv) = open_stream(&endpoint, &target).await?;
        write_hello(&mut send, self.config.platform).await?;
        expect_welcome(&mut recv).await?;
        Ok((send, recv))
    }

    async fn endpoint(&self, relay_url: Option<&RelayUrl>) -> Result<Endpoint, ShellyError> {
        let mut endpoint = self.endpoint.lock().await;
        if let Some(endpoint) = endpoint.as_ref() {
            return Ok(endpoint.clone());
        }

        let created = endpoint_for_secret(&self.secret_key, relay_url).await?;
        *endpoint = Some(created.clone());
        Ok(created)
    }
}

#[derive(uniffi::Object)]
/// Live terminal attachment to one daemon session.
pub struct AttachedSession {
    session_id: SessionId,
    send: Mutex<Option<SendStream>>,
    recv: Mutex<Option<RecvStream>>,
    initial_bytes: Mutex<Option<Vec<u8>>>,
    initial_seq: u64,
    last_seen_seq: AtomicU64,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum StreamDecision {
    Continue,
    StopForResync,
    StopCompleted,
}

#[uniffi::export(async_runtime = "tokio")]
impl AttachedSession {
    /// Sends raw input bytes to the attached PTY.
    pub async fn send_input(self: Arc<Self>, bytes: Vec<u8>) -> Result<(), ShellyError> {
        self.write_to_send_stream(&ClientToServerMsg::Input {
            session_id: self.session_id,
            bytes,
        })
        .await
    }

    /// Updates this mobile client's terminal viewport.
    pub async fn resize(self: Arc<Self>, cols: u16, rows: u16) -> Result<(), ShellyError> {
        self.write_to_send_stream(&ClientToServerMsg::Resize {
            session_id: self.session_id,
            size: ClientSize { cols, rows },
        })
        .await
    }

    /// Streams initial bytes, output, lag, state, and exit events to the callback.
    pub async fn subscribe(
        self: Arc<Self>,
        sink: Box<dyn ByteStreamSink>,
    ) -> Result<(), ShellyError> {
        if let Some(bytes) = self.initial_bytes.lock().await.take() {
            sink.on_initial_bytes(bytes);
        }
        let mut recv = self.take_recv().await?;
        loop {
            match self
                .dispatch_stream_message(read_msg::<ServerToClientMsg>(&mut recv).await?, &*sink)
            {
                Ok(StreamDecision::Continue) => {}
                Ok(StreamDecision::StopForResync | StreamDecision::StopCompleted) => break,
                Err(error) => {
                    self.replace_recv(recv).await;
                    return Err(error);
                }
            }
        }
        self.replace_recv(recv).await;
        Ok(())
    }

    /// Detaches this client without killing the desktop session.
    pub async fn detach(self: Arc<Self>) -> Result<(), ShellyError> {
        let mut guard = self.send.lock().await;
        let send = guard.as_mut().ok_or_else(|| {
            ShellyError::Protocol(
                "cannot detach because the terminal send stream is closed".to_string(),
            )
        })?;
        if let Err(error) = write_msg(send, &ClientToServerMsg::DetachSession).await {
            guard.take();
            return Err(error);
        }
        let _ = send.finish();
        Ok(())
    }

    /// Returns the byte offset after the initial attach payload.
    pub fn initial_seq(&self) -> u64 {
        self.initial_seq
    }

    /// Returns the latest raw PTY byte offset observed by this attachment.
    pub fn last_seen_seq(&self) -> u64 {
        self.last_seen_seq.load(Ordering::Acquire)
    }
}

impl AttachedSession {
    fn dispatch_stream_message(
        &self,
        message: ServerToClientMsg,
        sink: &dyn ByteStreamSink,
    ) -> Result<StreamDecision, ShellyError> {
        match message {
            ServerToClientMsg::Output { seq, bytes, .. } => {
                self.last_seen_seq.store(seq, Ordering::Release);
                sink.on_output(bytes);
                Ok(StreamDecision::Continue)
            }
            ServerToClientMsg::AgentStateChanged { state, .. } => {
                sink.on_agent_state(state.into());
                Ok(StreamDecision::Continue)
            }
            ServerToClientMsg::Lag { skipped_bytes, .. } => {
                sink.on_lag(skipped_bytes);
                Ok(StreamDecision::StopForResync)
            }
            ServerToClientMsg::SessionExited { exit_code, .. } => {
                sink.on_session_exited(exit_code);
                Ok(StreamDecision::StopCompleted)
            }
            ServerToClientMsg::Error { code, message } => Err(error_from_server(code, message)),
            _ => Ok(StreamDecision::Continue),
        }
    }

    async fn write_to_send_stream(&self, message: &ClientToServerMsg) -> Result<(), ShellyError> {
        let mut guard = self.send.lock().await;
        let send = guard.as_mut().ok_or_else(|| {
            ShellyError::Protocol(
                "cannot send terminal command because the daemon stream is closed".to_string(),
            )
        })?;
        if let Err(error) = write_msg(send, message).await {
            guard.take();
            return Err(error);
        }
        Ok(())
    }

    async fn take_recv(&self) -> Result<RecvStream, ShellyError> {
        self.recv.lock().await.take().ok_or_else(|| {
            ShellyError::Protocol(
                "cannot subscribe to terminal output because the receive stream is already in use"
                    .to_string(),
            )
        })
    }

    async fn replace_recv(&self, recv: RecvStream) {
        *self.recv.lock().await = Some(recv);
    }
}

impl DaemonTarget {
    fn from_ticket(ticket: &PairingTicket) -> Self {
        Self {
            node_id: ticket.node_id.clone(),
            relay_url: ticket.relay_url.clone(),
            addrs: ticket.addrs.clone(),
        }
    }

    fn from_config(config: &DaemonConfig) -> Self {
        Self {
            node_id: config.daemon_node_id.clone(),
            relay_url: config.relay_url.clone(),
            addrs: config.addrs.clone(),
        }
    }

    fn endpoint_addr(&self) -> Result<EndpointAddr, ShellyError> {
        let endpoint_id = self
            .node_id
            .parse()
            .map_err(|error: iroh::KeyParsingError| {
                ShellyError::Protocol(format!("stored daemon node id is invalid: {error}"))
            })?;
        let mut addrs = Vec::new();
        if let Some(relay_url) = &self.relay_url {
            let relay_url: RelayUrl =
                relay_url
                    .parse()
                    .map_err(|error: iroh::RelayUrlParseError| {
                        ShellyError::Protocol(format!(
                            "stored daemon relay URL is invalid: {error}"
                        ))
                    })?;
            addrs.push(TransportAddr::Relay(relay_url));
        }
        for addr in &self.addrs {
            let addr: SocketAddr = addr.parse().map_err(|error: std::net::AddrParseError| {
                ShellyError::Protocol(format!("stored daemon address is invalid: {error}"))
            })?;
            addrs.push(TransportAddr::Ip(addr));
        }
        Ok(EndpointAddr::from_parts(endpoint_id, addrs))
    }

    fn parsed_relay(&self) -> Result<Option<RelayUrl>, ShellyError> {
        self.relay_url
            .as_ref()
            .map(|relay_url| {
                relay_url
                    .parse::<RelayUrl>()
                    .map_err(|error: iroh::RelayUrlParseError| {
                        ShellyError::Protocol(format!(
                            "stored daemon relay URL is invalid: {error}"
                        ))
                    })
            })
            .transpose()
    }
}

async fn endpoint_for_secret(
    secret_key: &SecretKey,
    relay_url: Option<&RelayUrl>,
) -> Result<Endpoint, ShellyError> {
    // Minimal preset (crypto only) so the phone contacts no n0 server: no n0 DNS
    // publish/resolve, no n0 relays. When the daemon's relay is known (from the
    // pairing ticket or stored pairing) it becomes the only relay; otherwise the
    // endpoint is direct-only (same-network reconnect over the pinned addresses).
    let mut builder = Endpoint::builder(presets::Minimal).secret_key(secret_key.clone());
    if let Some(relay_url) = relay_url {
        builder = builder.relay_mode(RelayMode::custom([relay_url.clone()]));
    }
    builder.bind().await.map_err(|error| {
        ShellyError::Transport(format!(
            "failed to start Shelly mobile network endpoint: {error}"
        ))
    })
}

async fn open_stream(
    endpoint: &Endpoint,
    target: &DaemonTarget,
) -> Result<(SendStream, RecvStream), ShellyError> {
    // The relay (if any) is configured on the endpoint at build time. The target
    // address carries the daemon's stable relay URL plus any direct addresses as
    // connection candidates, so same-network reconnects still go direct.
    let conn = timeout(
        Duration::from_secs(15),
        endpoint.connect(target.endpoint_addr()?, SHELLY_ALPN),
    )
    .await
    .map_err(|_| ShellyError::Transport("timed out connecting to the paired daemon".to_string()))?
    .map_err(|error| {
        ShellyError::Transport(format!("failed to connect to the paired daemon: {error}"))
    })?;
    conn.open_bi().await.map_err(|error| {
        ShellyError::Transport(format!("failed to open daemon control stream: {error}"))
    })
}

async fn write_hello(send: &mut SendStream, platform: MobilePlatform) -> Result<(), ShellyError> {
    write_msg(
        send,
        &ClientToServerMsg::Hello {
            client_kind: platform.into(),
            client_version: env!("CARGO_PKG_VERSION").to_string(),
            protocol_version: CONTRACT_VERSION,
        },
    )
    .await
}

async fn expect_welcome(recv: &mut RecvStream) -> Result<(), ShellyError> {
    match read_msg::<ServerToClientMsg>(recv).await? {
        ServerToClientMsg::Welcome { .. } => Ok(()),
        ServerToClientMsg::Error { code, message } => Err(error_from_server(code, message)),
        other => Err(ShellyError::Protocol(format!(
            "unexpected daemon response during handshake: {other:?}"
        ))),
    }
}

async fn read_msg<T>(reader: &mut RecvStream) -> Result<T, ShellyError>
where
    T: DeserializeOwned,
{
    read_msg_from(reader).await
}

async fn read_msg_from<T, R>(reader: &mut R) -> Result<T, ShellyError>
where
    T: DeserializeOwned,
    R: AsyncRead + Unpin,
{
    let mut len_bytes = [0_u8; 4];
    reader.read_exact(&mut len_bytes).await.map_err(|error| {
        ShellyError::Transport(format!("failed to read daemon frame length: {error}"))
    })?;
    let len = u32::from_be_bytes(len_bytes) as usize;
    if len > max_frame_len() {
        return Err(ShellyError::Protocol(format!("frame too large: {len}")));
    }
    let mut payload = vec![0; len];
    reader.read_exact(&mut payload).await.map_err(|error| {
        ShellyError::Transport(format!("failed to read daemon frame payload: {error}"))
    })?;
    rmp_serde::from_slice(&payload)
        .map_err(|error| ShellyError::Protocol(format!("daemon frame payload is invalid: {error}")))
}

async fn write_msg<T>(writer: &mut SendStream, message: &T) -> Result<(), ShellyError>
where
    T: Serialize,
{
    write_msg_to(writer, message).await
}

async fn write_msg_to<T, W>(writer: &mut W, message: &T) -> Result<(), ShellyError>
where
    T: Serialize,
    W: AsyncWrite + Unpin,
{
    let payload = rmp_serde::to_vec_named(message).map_err(|error| {
        ShellyError::Protocol(format!("failed to encode daemon request: {error}"))
    })?;
    if payload.len() > max_frame_len() {
        return Err(ShellyError::Protocol(format!(
            "frame too large: {}",
            payload.len()
        )));
    }
    writer
        .write_all(&(payload.len() as u32).to_be_bytes())
        .await
        .map_err(|error| {
            ShellyError::Transport(format!("failed to write daemon frame length: {error}"))
        })?;
    writer.write_all(&payload).await.map_err(|error| {
        ShellyError::Transport(format!("failed to write daemon frame payload: {error}"))
    })?;
    Ok(())
}

#[derive(serde::Deserialize)]
/// Relay rendezvous response carrying the opaque encoded [`PairingTicket`].
struct ResolvePairingResponse {
    /// `sh1`-prefixed ticket string published by the daemon under this code.
    ticket_blob: String,
}

fn error_from_server(code: ErrorCode, message: String) -> ShellyError {
    match code {
        ErrorCode::ProtocolMismatch | ErrorCode::InvalidRequest => ShellyError::Protocol(message),
        ErrorCode::Unauthorized => ShellyError::Unauthorized(message),
        ErrorCode::Forbidden => ShellyError::Forbidden(message),
        ErrorCode::NotFound => ShellyError::NotFound(message),
        ErrorCode::Internal => ShellyError::Internal(message),
    }
}

#[cfg(target_os = "android")]
mod android_context {
    use jni::objects::JObject;
    use jni::{EnvUnowned, Outcome};
    use std::ffi::c_void;
    use std::sync::OnceLock;

    static ANDROID_CONTEXT_INIT: OnceLock<Result<(), String>> = OnceLock::new();

    #[unsafe(no_mangle)]
    pub extern "system" fn Java_app_shelly_android_core_ShellyNative_installAndroidContext<
        'local,
    >(
        mut env: EnvUnowned<'local>,
        _this: JObject<'local>,
        context: JObject<'local>,
    ) {
        let result = ANDROID_CONTEXT_INIT.get_or_init(|| {
            let outcome = env
                .with_env(|env| -> jni::errors::Result<()> {
                    let vm = env.get_java_vm()?;
                    let context = env.new_global_ref(context)?.into_raw();
                    unsafe {
                        ndk_context::initialize_android_context(
                            vm.get_raw().cast::<c_void>(),
                            context.cast::<c_void>(),
                        );
                    }
                    Ok(())
                })
                .into_outcome();

            match outcome {
                Outcome::Ok(()) => Ok(()),
                Outcome::Err(error) => Err(error.to_string()),
                Outcome::Panic(_) => Err("panic while installing Android JNI context".to_string()),
            }
        });

        if let Err(error) = result {
            throw_java_runtime_exception(&mut env, error);
        }
    }

    fn throw_java_runtime_exception(env: &mut EnvUnowned<'_>, message: &str) {
        let message = format!("Shelly Android context initialization failed: {message}");
        let _ = env
            .with_env(|env| -> jni::errors::Result<()> {
                let _ = env.throw(message);
                Ok(())
            })
            .into_outcome();
    }
}

impl From<MobilePlatform> for ClientKind {
    fn from(platform: MobilePlatform) -> Self {
        match platform {
            MobilePlatform::Ios => ClientKind::IosApp,
            MobilePlatform::Android => ClientKind::AndroidApp,
        }
    }
}

impl From<PushPlatform> for ProtocolPushPlatform {
    fn from(platform: PushPlatform) -> Self {
        match platform {
            PushPlatform::Apns => ProtocolPushPlatform::Apns,
            PushPlatform::Fcm => ProtocolPushPlatform::Fcm,
        }
    }
}

impl From<ProtocolAgentState> for AgentStateFfi {
    fn from(state: ProtocolAgentState) -> Self {
        match state {
            ProtocolAgentState::Idle => AgentStateFfi::Idle,
            ProtocolAgentState::Working => AgentStateFfi::Working,
            ProtocolAgentState::AwaitingInput => AgentStateFfi::AwaitingInput,
            ProtocolAgentState::Crashed => AgentStateFfi::Crashed,
        }
    }
}

impl From<ProtocolSessionSummary> for SessionSummaryFfi {
    fn from(summary: ProtocolSessionSummary) -> Self {
        Self {
            id: summary.id.to_string(),
            name: summary.name,
            command: summary.command,
            cwd: summary.cwd.display().to_string(),
            created_at: summary.created_at,
            last_activity: summary.last_activity,
            state: summary.state.into(),
            last_line: summary.last_line,
            model: summary.model,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex as StdMutex;
    use tokio::io::duplex;

    #[derive(Clone, Debug, Eq, PartialEq)]
    enum SinkEvent {
        Initial(Vec<u8>),
        Output(Vec<u8>),
        AgentState(AgentStateFfi),
        Lag(u64),
        Exited(i32),
    }

    #[derive(Default)]
    struct RecordingSink {
        events: StdMutex<Vec<SinkEvent>>,
    }

    impl RecordingSink {
        fn events(&self) -> Vec<SinkEvent> {
            self.events.lock().expect("events lock poisoned").clone()
        }
    }

    impl ByteStreamSink for RecordingSink {
        fn on_initial_bytes(&self, bytes: Vec<u8>) {
            self.events
                .lock()
                .expect("events lock poisoned")
                .push(SinkEvent::Initial(bytes));
        }

        fn on_output(&self, bytes: Vec<u8>) {
            self.events
                .lock()
                .expect("events lock poisoned")
                .push(SinkEvent::Output(bytes));
        }

        fn on_agent_state(&self, state: AgentStateFfi) {
            self.events
                .lock()
                .expect("events lock poisoned")
                .push(SinkEvent::AgentState(state));
        }

        fn on_lag(&self, skipped_bytes: u64) {
            self.events
                .lock()
                .expect("events lock poisoned")
                .push(SinkEvent::Lag(skipped_bytes));
        }

        fn on_session_exited(&self, code: i32) {
            self.events
                .lock()
                .expect("events lock poisoned")
                .push(SinkEvent::Exited(code));
        }
    }

    fn sample_ticket() -> PairingTicket {
        PairingTicket {
            code: "AB234".to_string(),
            node_id: "node".to_string(),
            relay_url: Some("https://relay.example".to_string()),
            addrs: vec!["127.0.0.1:9000".to_string()],
            expires_at: 1,
        }
    }

    #[test]
    fn pairing_ticket_round_trips_through_qr_string() {
        let ticket = sample_ticket();
        let encoded = ticket.encode().expect("encode ticket");
        assert!(encoded.starts_with("sh1"));
        assert_eq!(PairingTicket::decode(&encoded).unwrap(), ticket);
    }

    #[test]
    fn pair_with_qr_input_tolerates_trailing_newline() {
        let ticket = sample_ticket();
        let encoded = ticket.encode().expect("encode ticket");
        // pair_with_qr trims its input before decoding; a scanner that appends a
        // trailing newline must still resolve to the same ticket.
        let scanned = format!("{encoded}\n");
        assert_eq!(PairingTicket::decode(scanned.trim()).unwrap(), ticket);
    }

    #[test]
    fn rejects_invalid_device_secret_key() {
        let result = ShellyClient::new(ClientConfig {
            device_name: "phone".to_string(),
            platform: MobilePlatform::Ios,
            device_secret_key: Some(vec![1, 2, 3]),
            paired_daemon: None,
            relay_control_url: None,
        });

        assert!(matches!(result, Err(ShellyError::InvalidConfig(_))));
    }

    #[tokio::test]
    async fn mobile_messagepack_frame_helpers_round_trip_length_prefixed_transport() {
        let (mut writer, mut reader) = duplex(1024);

        write_msg_to(&mut writer, &ClientToServerMsg::Ping { seq: 9 })
            .await
            .unwrap();
        drop(writer);

        let decoded: ClientToServerMsg = read_msg_from(&mut reader).await.unwrap();

        assert_eq!(decoded, ClientToServerMsg::Ping { seq: 9 });
    }

    #[tokio::test]
    async fn mobile_messagepack_frame_reader_rejects_oversized_length_before_allocating() {
        let (mut writer, mut reader) = duplex(16);
        writer
            .write_all(&((max_frame_len() as u32 + 1).to_be_bytes()))
            .await
            .unwrap();
        drop(writer);

        let error = read_msg_from::<ClientToServerMsg, _>(&mut reader)
            .await
            .unwrap_err();

        assert!(
            matches!(error, ShellyError::Protocol(message) if message.contains("frame too large"))
        );
    }

    #[tokio::test]
    async fn mobile_messagepack_frame_reader_rejects_incomplete_payload() {
        let (mut writer, mut reader) = duplex(16);
        writer.write_all(&8_u32.to_be_bytes()).await.unwrap();
        writer.write_all(&[0]).await.unwrap();
        drop(writer);

        let error = read_msg_from::<ClientToServerMsg, _>(&mut reader)
            .await
            .unwrap_err();

        assert!(matches!(error, ShellyError::Transport(_)));
    }

    #[test]
    fn stream_output_advances_mobile_reconnect_offset_without_decoding_bytes() {
        let session_id = SessionId::new();
        let attached = test_attached_session(session_id, 7);
        let sink = RecordingSink::default();
        let raw_bytes = vec![0x1b, b'[', b'3', b'1', b'm', 0xff, b'\r', b'\n'];

        let decision = attached
            .dispatch_stream_message(
                ServerToClientMsg::Output {
                    session_id,
                    seq: 42,
                    bytes: raw_bytes.clone(),
                },
                &sink,
            )
            .expect("dispatch output");

        assert_eq!(decision, StreamDecision::Continue);
        assert_eq!(attached.last_seen_seq(), 42);
        assert_eq!(sink.events(), vec![SinkEvent::Output(raw_bytes)]);
    }

    #[test]
    fn yes_head_10000_scale_stream_delivers_all_bytes_without_offset_drift() {
        let session_id = SessionId::new();
        let attached = test_attached_session(session_id, 0);
        let sink = RecordingSink::default();
        let mut expected_stream = Vec::with_capacity(20_000);
        let mut seq = 0;

        for _ in 0..100 {
            let mut chunk = Vec::with_capacity(200);
            for _ in 0..100 {
                chunk.extend_from_slice(b"y\n");
            }
            seq += chunk.len() as u64;
            expected_stream.extend_from_slice(&chunk);

            let decision = attached
                .dispatch_stream_message(
                    ServerToClientMsg::Output {
                        session_id,
                        seq,
                        bytes: chunk,
                    },
                    &sink,
                )
                .expect("dispatch output chunk");

            assert_eq!(decision, StreamDecision::Continue);
            assert_eq!(attached.last_seen_seq(), seq);
        }

        let mut actual_stream = Vec::with_capacity(expected_stream.len());
        for event in sink.events() {
            match event {
                SinkEvent::Output(bytes) => actual_stream.extend(bytes),
                other => panic!("unexpected sink event: {other:?}"),
            }
        }

        assert_eq!(actual_stream, expected_stream);
        assert_eq!(actual_stream.len(), 20_000);
        assert_eq!(attached.last_seen_seq(), 20_000);
    }

    #[test]
    fn lag_event_notifies_native_ui_and_stops_for_resync() {
        let session_id = SessionId::new();
        let attached = test_attached_session(session_id, 9);
        let sink = RecordingSink::default();

        let decision = attached
            .dispatch_stream_message(
                ServerToClientMsg::Lag {
                    session_id,
                    skipped_bytes: 3,
                },
                &sink,
            )
            .expect("dispatch lag");

        assert_eq!(decision, StreamDecision::StopForResync);
        assert_eq!(attached.last_seen_seq(), 9);
        assert_eq!(sink.events(), vec![SinkEvent::Lag(3)]);
    }

    fn test_attached_session(session_id: SessionId, seq: u64) -> AttachedSession {
        AttachedSession {
            session_id,
            send: tokio::sync::Mutex::new(None),
            recv: tokio::sync::Mutex::new(None),
            initial_bytes: tokio::sync::Mutex::new(None),
            initial_seq: seq,
            last_seen_seq: std::sync::atomic::AtomicU64::new(seq),
        }
    }
}

uniffi::setup_scaffolding!();
