#![deny(missing_docs)]
//! UniFFI mobile client surface for native iOS and Android apps.
//!
//! The API intentionally exposes only pair/list/attach/input/resize/detach and
//! push-token registration. It does not expose session creation, command
//! selection, or session termination, preserving the v1 mobile security boundary.

use fieldwork_protocol::{
    AgentState as ProtocolAgentState, CONTRACT_VERSION, ClientKind, ClientSize, ClientToServerMsg,
    ErrorCode, PairingPayload, PushPlatform as ProtocolPushPlatform, ServerToClientMsg, SessionId,
    SessionSummary as ProtocolSessionSummary, max_frame_len,
};
use iroh::endpoint::{RecvStream, SendStream, presets};
use iroh::{Endpoint, EndpointAddr, RelayUrl, SecretKey, TransportAddr};
use serde::{Serialize, de::DeserializeOwned};
use std::net::SocketAddr;
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};
use tokio::sync::Mutex;

const FIELDWORK_ALPN: &[u8] = b"fieldwork/1";

#[derive(Clone, Debug, uniffi::Record)]
/// Configuration used to construct a mobile Fieldwork client.
pub struct ClientConfig {
    /// User-facing device name shown in the desktop approval prompt.
    pub device_name: String,
    /// Native platform, used to choose the protocol client kind.
    pub platform: MobilePlatform,
    /// Persisted 32-byte iroh secret key; omitted on first launch to generate one.
    pub device_secret_key: Option<Vec<u8>>,
    /// Persisted daemon connection target after successful pairing.
    pub paired_daemon: Option<DaemonConfig>,
}

#[derive(Clone, Copy, Debug, uniffi::Enum)]
/// Native mobile platform using the shared core.
pub enum MobilePlatform {
    /// iOS app.
    Ios,
    /// Android app.
    Android,
}

#[derive(Clone, Copy, Debug, uniffi::Enum)]
/// Push provider for a token registered by the native app.
pub enum PushPlatform {
    /// Apple Push Notification service token.
    Apns,
    /// Firebase Cloud Messaging token.
    Fcm,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, uniffi::Enum)]
/// Agent state enum exported through UniFFI-safe names.
pub enum AgentStateFfi {
    /// No recent activity or pending input.
    Idle,
    /// PTY output or input indicates active work.
    Working,
    /// Claude/Codex is waiting for user input or approval.
    AwaitingInput,
    /// The session exited abnormally.
    Crashed,
}

#[derive(Clone, Debug, uniffi::Record)]
/// Result of successful QR pairing, persisted by the native app.
pub struct DaemonInfo {
    /// Daemon iroh node id.
    pub daemon_node_id: String,
    /// Relay URL advertised by the daemon, when available.
    pub relay_url: Option<String>,
    /// Direct addresses advertised by the daemon.
    pub addrs: Vec<String>,
    /// Mobile device iroh node id generated by this core.
    pub device_node_id: String,
    /// 32-byte mobile iroh secret key to persist in platform secure storage.
    pub device_secret_key: Vec<u8>,
}

#[derive(Clone, Debug, uniffi::Record)]
/// Persisted daemon target needed to reconnect after pairing.
pub struct DaemonConfig {
    /// Paired daemon iroh node id.
    pub daemon_node_id: String,
    /// Relay URL advertised during pairing, when available.
    pub relay_url: Option<String>,
    /// Direct addresses advertised during pairing.
    pub addrs: Vec<String>,
}

#[derive(Clone, Debug, uniffi::Record)]
/// Dashboard summary exported to native session lists.
pub struct SessionSummaryFfi {
    /// Session UUID string.
    pub id: String,
    /// User-facing session label.
    pub name: String,
    /// Command and arguments running on the desktop.
    pub command: Vec<String>,
    /// Desktop working directory as display text.
    pub cwd: String,
    /// UTC creation time in milliseconds since the Unix epoch.
    pub created_at: u64,
    /// UTC last-activity time in milliseconds since the Unix epoch.
    pub last_activity: u64,
    /// Current inferred agent/session state.
    pub state: AgentStateFfi,
    /// Sanitized, truncated terminal preview for dashboard cards.
    pub last_line: Option<String>,
    /// Optional AI model label.
    pub model: Option<String>,
}

#[derive(Debug, thiserror::Error, uniffi::Error)]
#[uniffi(flat_error)]
/// Error type mapped across Swift and Kotlin bindings.
pub enum FieldworkError {
    /// Client configuration or caller input is invalid.
    #[error("invalid config: {0}")]
    InvalidConfig(String),
    /// iroh transport or stream IO failed.
    #[error("transport error: {0}")]
    Transport(String),
    /// The daemon returned an unexpected or invalid protocol response.
    #[error("protocol error: {0}")]
    Protocol(String),
    /// The daemon rejected the client identity.
    #[error("unauthorized: {0}")]
    Unauthorized(String),
    /// The client is authenticated but not allowed to perform the operation.
    #[error("forbidden: {0}")]
    Forbidden(String),
    /// The requested session or resource does not exist.
    #[error("not found: {0}")]
    NotFound(String),
    /// Internal daemon or mobile-core error.
    #[error("internal error: {0}")]
    Internal(String),
}

#[uniffi::export(callback_interface)]
/// Callback interface for session-list subscriptions.
pub trait SessionListSink: Send + Sync {
    /// Receives a complete replacement session list.
    fn on_update(&self, sessions: Vec<SessionSummaryFfi>);
}

#[uniffi::export(callback_interface)]
/// Callback interface for attached terminal byte streams.
pub trait ByteStreamSink: Send + Sync {
    /// Receives replay or synthetic snapshot bytes immediately after attach.
    fn on_initial_bytes(&self, bytes: Vec<u8>);
    /// Receives raw PTY output bytes.
    fn on_output(&self, bytes: Vec<u8>);
    /// Receives an inferred agent-state change.
    fn on_agent_state(&self, state: AgentStateFfi);
    /// Receives a subscriber-overflow signal; native UI should reattach/resync.
    ///
    /// The v1 wire field is named `skipped_bytes`, but the value is the number
    /// of daemon broadcast messages skipped by the receiver.
    fn on_lag(&self, skipped_bytes: u64);
    /// Receives the process exit code when the session terminates.
    fn on_session_exited(&self, code: i32);
}

#[derive(uniffi::Object)]
/// Mobile client object that owns the device iroh identity.
pub struct FieldworkClient {
    config: ClientConfig,
    secret_key: SecretKey,
    daemon: Mutex<Option<DaemonTarget>>,
    endpoint: Mutex<Option<Endpoint>>,
    connected: Mutex<bool>,
}

#[derive(Clone, Debug)]
struct DaemonTarget {
    node_id: String,
    relay_url: Option<String>,
    addrs: Vec<String>,
}

#[uniffi::export(async_runtime = "tokio")]
impl FieldworkClient {
    #[uniffi::constructor]
    /// Creates a client, generating a device key when no persisted key is supplied.
    pub fn new(config: ClientConfig) -> Result<Arc<Self>, FieldworkError> {
        let secret_key = match &config.device_secret_key {
            Some(bytes) => SecretKey::from_bytes(&bytes.as_slice().try_into().map_err(|_| {
                FieldworkError::InvalidConfig("device_secret_key must be 32 bytes".to_string())
            })?),
            None => SecretKey::generate(),
        };

        let daemon = config.paired_daemon.as_ref().map(DaemonTarget::from_config);

        Ok(Arc::new(Self {
            config,
            secret_key,
            daemon: Mutex::new(daemon),
            endpoint: Mutex::new(None),
            connected: Mutex::new(false),
        }))
    }

    /// Pairs with a daemon using the JSON payload embedded in the desktop QR.
    pub async fn pair_with_qr(
        self: Arc<Self>,
        qr_payload: String,
    ) -> Result<DaemonInfo, FieldworkError> {
        let payload: PairingPayload = serde_json::from_str(extract_json_payload(&qr_payload)?)
            .map_err(|error| FieldworkError::Protocol(error.to_string()))?;
        let target = DaemonTarget::from_payload(&payload);
        let endpoint = self.endpoint().await?;
        let (mut send, mut recv) = open_stream(&endpoint, &target).await?;

        write_hello(&mut send, self.config.platform).await?;
        expect_welcome(&mut recv).await?;
        write_msg(
            &mut send,
            &ClientToServerMsg::PairWithToken {
                pair_token: payload.pair_token,
                device_name: self.config.device_name.clone(),
                device_node_id: endpoint.id().to_string(),
            },
        )
        .await?;

        match read_msg::<ServerToClientMsg>(&mut recv).await? {
            ServerToClientMsg::PairingComplete { daemon_node_id } => {
                *self.daemon.lock().await = Some(target.clone());
                *self.connected.lock().await = true;
                Ok(DaemonInfo {
                    daemon_node_id,
                    relay_url: target.relay_url,
                    addrs: target.addrs,
                    device_node_id: endpoint.id().to_string(),
                    device_secret_key: self.secret_key.to_bytes().to_vec(),
                })
            }
            ServerToClientMsg::Error { code, message } => Err(error_from_server(code, message)),
            other => Err(FieldworkError::Protocol(format!(
                "unexpected daemon response during pairing: {other:?}"
            ))),
        }
    }

    /// Connects to a previously paired daemon and verifies authorization with a ping.
    pub async fn connect(self: Arc<Self>) -> Result<(), FieldworkError> {
        let endpoint = endpoint_for_secret(&self.secret_key).await?;
        let target = self.daemon_target().await?;
        let (mut send, mut recv) = open_stream(&endpoint, &target).await?;
        write_hello(&mut send, self.config.platform).await?;
        expect_welcome(&mut recv).await?;
        write_msg(&mut send, &ClientToServerMsg::Ping { seq: 1 }).await?;
        match read_msg::<ServerToClientMsg>(&mut recv).await? {
            ServerToClientMsg::Pong { seq: 1 } => {
                *self.connected.lock().await = true;
                Ok(())
            }
            ServerToClientMsg::Error { code, message } => Err(error_from_server(code, message)),
            other => Err(FieldworkError::Protocol(format!(
                "unexpected daemon response during connect: {other:?}"
            ))),
        }
    }

    /// Marks the client disconnected locally; active attach streams are closed by their owners.
    pub async fn disconnect(self: Arc<Self>) -> Result<(), FieldworkError> {
        *self.connected.lock().await = false;
        Ok(())
    }

    /// Fetches the current session list from the paired daemon.
    pub async fn list_sessions(self: Arc<Self>) -> Result<Vec<SessionSummaryFfi>, FieldworkError> {
        let (mut send, mut recv) = self.open_authenticated_stream().await?;
        write_msg(&mut send, &ClientToServerMsg::ListSessions).await?;
        match read_msg::<ServerToClientMsg>(&mut recv).await? {
            ServerToClientMsg::SessionList { sessions } => {
                Ok(sessions.into_iter().map(Into::into).collect())
            }
            ServerToClientMsg::Error { code, message } => Err(error_from_server(code, message)),
            other => Err(FieldworkError::Protocol(format!(
                "unexpected daemon response to ListSessions: {other:?}"
            ))),
        }
    }

    /// Attaches to a desktop-created session by id.
    pub async fn attach_session(
        self: Arc<Self>,
        id: String,
    ) -> Result<Arc<AttachedSession>, FieldworkError> {
        self.attach_session_from(id, None).await
    }

    /// Attaches to a desktop-created session and asks the daemon to replay from a byte offset.
    pub async fn attach_session_from(
        self: Arc<Self>,
        id: String,
        last_seen_seq: Option<u64>,
    ) -> Result<Arc<AttachedSession>, FieldworkError> {
        let session_id = id
            .parse::<SessionId>()
            .map_err(|error| FieldworkError::InvalidConfig(error.to_string()))?;
        let (mut send, mut recv) = self.open_authenticated_stream().await?;
        write_msg(
            &mut send,
            &ClientToServerMsg::AttachSession {
                session_id,
                size: ClientSize { cols: 80, rows: 24 },
                last_seen_seq,
            },
        )
        .await?;
        match read_msg::<ServerToClientMsg>(&mut recv).await? {
            ServerToClientMsg::Attached {
                initial_bytes, seq, ..
            } => Ok(Arc::new(AttachedSession {
                session_id,
                send: Mutex::new(Some(send)),
                recv: Mutex::new(Some(recv)),
                initial_bytes: Mutex::new(Some(initial_bytes)),
                initial_seq: seq,
                last_seen_seq: AtomicU64::new(seq),
            })),
            ServerToClientMsg::Error { code, message } => Err(error_from_server(code, message)),
            other => Err(FieldworkError::Protocol(format!(
                "unexpected daemon response to AttachSession: {other:?}"
            ))),
        }
    }

    /// Emits the current session list through a callback.
    pub async fn subscribe_sessions(
        self: Arc<Self>,
        sink: Box<dyn SessionListSink>,
    ) -> Result<(), FieldworkError> {
        let (mut send, mut recv) = self.open_authenticated_stream().await?;
        write_msg(&mut send, &ClientToServerMsg::SubscribeSessions).await?;
        loop {
            match read_msg::<ServerToClientMsg>(&mut recv).await? {
                ServerToClientMsg::SessionList { sessions } => {
                    sink.on_update(sessions.into_iter().map(Into::into).collect());
                }
                ServerToClientMsg::Error { code, message } => {
                    return Err(error_from_server(code, message));
                }
                other => {
                    return Err(FieldworkError::Protocol(format!(
                        "unexpected daemon response to SubscribeSessions: {other:?}"
                    )));
                }
            }
        }
    }

    /// Registers the native APNs/FCM token with the paired daemon.
    pub async fn register_push_token(
        self: Arc<Self>,
        platform: PushPlatform,
        token: String,
    ) -> Result<(), FieldworkError> {
        let (mut send, mut recv) = self.open_authenticated_stream().await?;
        write_msg(
            &mut send,
            &ClientToServerMsg::RegisterPushToken {
                platform: platform.into(),
                token,
            },
        )
        .await?;
        match read_msg::<ServerToClientMsg>(&mut recv).await? {
            ServerToClientMsg::Pong { .. } => Ok(()),
            ServerToClientMsg::Error { code, message } => Err(error_from_server(code, message)),
            other => Err(FieldworkError::Protocol(format!(
                "unexpected daemon response to RegisterPushToken: {other:?}"
            ))),
        }
    }
}

impl FieldworkClient {
    async fn daemon_target(&self) -> Result<DaemonTarget, FieldworkError> {
        self.daemon
            .lock()
            .await
            .clone()
            .ok_or_else(|| FieldworkError::InvalidConfig("client is not paired".to_string()))
    }

    async fn open_authenticated_stream(&self) -> Result<(SendStream, RecvStream), FieldworkError> {
        let endpoint = self.endpoint().await?;
        let target = self.daemon_target().await?;
        let (mut send, mut recv) = open_stream(&endpoint, &target).await?;
        write_hello(&mut send, self.config.platform).await?;
        expect_welcome(&mut recv).await?;
        Ok((send, recv))
    }

    async fn endpoint(&self) -> Result<Endpoint, FieldworkError> {
        let mut endpoint = self.endpoint.lock().await;
        if let Some(endpoint) = endpoint.as_ref() {
            return Ok(endpoint.clone());
        }

        let created = endpoint_for_secret(&self.secret_key).await?;
        *endpoint = Some(created.clone());
        Ok(created)
    }
}

#[derive(uniffi::Object)]
/// Live terminal attachment to one daemon session.
pub struct AttachedSession {
    session_id: SessionId,
    send: Mutex<Option<SendStream>>,
    recv: Mutex<Option<RecvStream>>,
    initial_bytes: Mutex<Option<Vec<u8>>>,
    initial_seq: u64,
    last_seen_seq: AtomicU64,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum StreamDecision {
    Continue,
    StopForResync,
    StopCompleted,
}

#[uniffi::export(async_runtime = "tokio")]
impl AttachedSession {
    /// Sends raw input bytes to the attached PTY.
    pub async fn send_input(self: Arc<Self>, bytes: Vec<u8>) -> Result<(), FieldworkError> {
        let mut send = self.take_send().await?;
        write_msg(
            &mut send,
            &ClientToServerMsg::Input {
                session_id: self.session_id,
                bytes,
            },
        )
        .await?;
        self.replace_send(send).await;
        Ok(())
    }

    /// Updates this mobile client's terminal viewport.
    pub async fn resize(self: Arc<Self>, cols: u16, rows: u16) -> Result<(), FieldworkError> {
        let mut send = self.take_send().await?;
        write_msg(
            &mut send,
            &ClientToServerMsg::Resize {
                session_id: self.session_id,
                size: ClientSize { cols, rows },
            },
        )
        .await?;
        self.replace_send(send).await;
        Ok(())
    }

    /// Streams initial bytes, output, lag, state, and exit events to the callback.
    pub async fn subscribe(
        self: Arc<Self>,
        sink: Box<dyn ByteStreamSink>,
    ) -> Result<(), FieldworkError> {
        if let Some(bytes) = self.initial_bytes.lock().await.take() {
            sink.on_initial_bytes(bytes);
        }
        let mut recv = self.take_recv().await?;
        loop {
            match self
                .dispatch_stream_message(read_msg::<ServerToClientMsg>(&mut recv).await?, &*sink)
            {
                Ok(StreamDecision::Continue) => {}
                Ok(StreamDecision::StopForResync | StreamDecision::StopCompleted) => break,
                Err(error) => {
                    self.replace_recv(recv).await;
                    return Err(error);
                }
            }
        }
        self.replace_recv(recv).await;
        Ok(())
    }

    /// Detaches this client without killing the desktop session.
    pub async fn detach(self: Arc<Self>) -> Result<(), FieldworkError> {
        let mut send = self.take_send().await?;
        write_msg(&mut send, &ClientToServerMsg::DetachSession).await?;
        let _ = send.finish();
        self.replace_send(send).await;
        Ok(())
    }

    /// Returns the byte offset after the initial attach payload.
    pub fn initial_seq(&self) -> u64 {
        self.initial_seq
    }

    /// Returns the latest raw PTY byte offset observed by this attachment.
    pub fn last_seen_seq(&self) -> u64 {
        self.last_seen_seq.load(Ordering::Acquire)
    }
}

impl AttachedSession {
    fn dispatch_stream_message(
        &self,
        message: ServerToClientMsg,
        sink: &dyn ByteStreamSink,
    ) -> Result<StreamDecision, FieldworkError> {
        match message {
            ServerToClientMsg::Output { seq, bytes, .. } => {
                self.last_seen_seq.store(seq, Ordering::Release);
                sink.on_output(bytes);
                Ok(StreamDecision::Continue)
            }
            ServerToClientMsg::AgentStateChanged { state, .. } => {
                sink.on_agent_state(state.into());
                Ok(StreamDecision::Continue)
            }
            ServerToClientMsg::Lag { skipped_bytes, .. } => {
                sink.on_lag(skipped_bytes);
                Ok(StreamDecision::StopForResync)
            }
            ServerToClientMsg::SessionExited { exit_code, .. } => {
                sink.on_session_exited(exit_code);
                Ok(StreamDecision::StopCompleted)
            }
            ServerToClientMsg::Error { code, message } => Err(error_from_server(code, message)),
            _ => Ok(StreamDecision::Continue),
        }
    }

    async fn take_send(&self) -> Result<SendStream, FieldworkError> {
        self.send
            .lock()
            .await
            .take()
            .ok_or_else(|| FieldworkError::Protocol("send stream is already in use".to_string()))
    }

    async fn replace_send(&self, send: SendStream) {
        *self.send.lock().await = Some(send);
    }

    async fn take_recv(&self) -> Result<RecvStream, FieldworkError> {
        self.recv
            .lock()
            .await
            .take()
            .ok_or_else(|| FieldworkError::Protocol("receive stream is already in use".to_string()))
    }

    async fn replace_recv(&self, recv: RecvStream) {
        *self.recv.lock().await = Some(recv);
    }
}

impl DaemonTarget {
    fn from_payload(payload: &PairingPayload) -> Self {
        Self {
            node_id: payload.node_id.clone(),
            relay_url: payload.relay_url.clone(),
            addrs: payload.addrs.clone(),
        }
    }

    fn from_config(config: &DaemonConfig) -> Self {
        Self {
            node_id: config.daemon_node_id.clone(),
            relay_url: config.relay_url.clone(),
            addrs: config.addrs.clone(),
        }
    }

    fn endpoint_addr(&self) -> Result<EndpointAddr, FieldworkError> {
        let endpoint_id = self
            .node_id
            .parse()
            .map_err(|error: iroh::KeyParsingError| FieldworkError::Protocol(error.to_string()))?;
        let mut addrs = Vec::new();
        if let Some(relay_url) = &self.relay_url {
            let relay_url: RelayUrl =
                relay_url
                    .parse()
                    .map_err(|error: iroh::RelayUrlParseError| {
                        FieldworkError::Protocol(error.to_string())
                    })?;
            addrs.push(TransportAddr::Relay(relay_url));
        }
        for addr in &self.addrs {
            let addr: SocketAddr = addr.parse().map_err(|error: std::net::AddrParseError| {
                FieldworkError::Protocol(error.to_string())
            })?;
            addrs.push(TransportAddr::Ip(addr));
        }
        Ok(EndpointAddr::from_parts(endpoint_id, addrs))
    }
}

async fn endpoint_for_secret(secret_key: &SecretKey) -> Result<Endpoint, FieldworkError> {
    Endpoint::builder(presets::N0)
        .secret_key(secret_key.clone())
        .bind()
        .await
        .map_err(|error| FieldworkError::Transport(error.to_string()))
}

async fn open_stream(
    endpoint: &Endpoint,
    target: &DaemonTarget,
) -> Result<(SendStream, RecvStream), FieldworkError> {
    let conn = endpoint
        .connect(target.endpoint_addr()?, FIELDWORK_ALPN)
        .await
        .map_err(|error| FieldworkError::Transport(error.to_string()))?;
    conn.open_bi()
        .await
        .map_err(|error| FieldworkError::Transport(error.to_string()))
}

async fn write_hello(
    send: &mut SendStream,
    platform: MobilePlatform,
) -> Result<(), FieldworkError> {
    write_msg(
        send,
        &ClientToServerMsg::Hello {
            client_kind: platform.into(),
            client_version: env!("CARGO_PKG_VERSION").to_string(),
            protocol_version: CONTRACT_VERSION,
        },
    )
    .await
}

async fn expect_welcome(recv: &mut RecvStream) -> Result<(), FieldworkError> {
    match read_msg::<ServerToClientMsg>(recv).await? {
        ServerToClientMsg::Welcome { .. } => Ok(()),
        ServerToClientMsg::Error { code, message } => Err(error_from_server(code, message)),
        other => Err(FieldworkError::Protocol(format!(
            "unexpected daemon response during handshake: {other:?}"
        ))),
    }
}

async fn read_msg<T>(reader: &mut RecvStream) -> Result<T, FieldworkError>
where
    T: DeserializeOwned,
{
    let mut len_bytes = [0_u8; 4];
    reader
        .read_exact(&mut len_bytes)
        .await
        .map_err(|error| FieldworkError::Transport(error.to_string()))?;
    let len = u32::from_be_bytes(len_bytes) as usize;
    if len > max_frame_len() {
        return Err(FieldworkError::Protocol(format!("frame too large: {len}")));
    }
    let mut payload = vec![0; len];
    reader
        .read_exact(&mut payload)
        .await
        .map_err(|error| FieldworkError::Transport(error.to_string()))?;
    rmp_serde::from_slice(&payload).map_err(|error| FieldworkError::Protocol(error.to_string()))
}

async fn write_msg<T>(writer: &mut SendStream, message: &T) -> Result<(), FieldworkError>
where
    T: Serialize,
{
    let payload = rmp_serde::to_vec_named(message)
        .map_err(|error| FieldworkError::Protocol(error.to_string()))?;
    if payload.len() > max_frame_len() {
        return Err(FieldworkError::Protocol(format!(
            "frame too large: {}",
            payload.len()
        )));
    }
    writer
        .write_all(&(payload.len() as u32).to_be_bytes())
        .await
        .map_err(|error| FieldworkError::Transport(error.to_string()))?;
    writer
        .write_all(&payload)
        .await
        .map_err(|error| FieldworkError::Transport(error.to_string()))?;
    Ok(())
}

fn extract_json_payload(input: &str) -> Result<&str, FieldworkError> {
    let start = input
        .find('{')
        .ok_or_else(|| FieldworkError::Protocol("QR payload does not contain JSON".to_string()))?;
    let end = input
        .rfind('}')
        .ok_or_else(|| FieldworkError::Protocol("QR payload does not contain JSON".to_string()))?;
    if end < start {
        return Err(FieldworkError::Protocol(
            "QR payload does not contain JSON".to_string(),
        ));
    }
    Ok(&input[start..=end])
}

fn error_from_server(code: ErrorCode, message: String) -> FieldworkError {
    match code {
        ErrorCode::ProtocolMismatch | ErrorCode::InvalidRequest => {
            FieldworkError::Protocol(message)
        }
        ErrorCode::Unauthorized => FieldworkError::Unauthorized(message),
        ErrorCode::Forbidden => FieldworkError::Forbidden(message),
        ErrorCode::NotFound => FieldworkError::NotFound(message),
        ErrorCode::Internal => FieldworkError::Internal(message),
    }
}

#[cfg(target_os = "android")]
mod android_context {
    use jni::objects::JObject;
    use jni::{EnvUnowned, Outcome};
    use std::ffi::c_void;
    use std::sync::OnceLock;

    static ANDROID_CONTEXT_INIT: OnceLock<Result<(), String>> = OnceLock::new();

    #[unsafe(no_mangle)]
    pub extern "system" fn Java_app_fieldwork_android_core_FieldworkNative_installAndroidContext<
        'local,
    >(
        mut env: EnvUnowned<'local>,
        _this: JObject<'local>,
        context: JObject<'local>,
    ) {
        let result = ANDROID_CONTEXT_INIT.get_or_init(|| {
            let outcome = env
                .with_env(|env| -> jni::errors::Result<()> {
                    let vm = env.get_java_vm()?;
                    let context = env.new_global_ref(context)?.into_raw();
                    unsafe {
                        ndk_context::initialize_android_context(
                            vm.get_raw().cast::<c_void>(),
                            context.cast::<c_void>(),
                        );
                    }
                    Ok(())
                })
                .into_outcome();

            match outcome {
                Outcome::Ok(()) => Ok(()),
                Outcome::Err(error) => Err(error.to_string()),
                Outcome::Panic(_) => Err("panic while installing Android JNI context".to_string()),
            }
        });

        if let Err(error) = result {
            throw_java_runtime_exception(&mut env, error);
        }
    }

    fn throw_java_runtime_exception(env: &mut EnvUnowned<'_>, message: &str) {
        let message = format!("Fieldwork Android context initialization failed: {message}");
        let _ = env
            .with_env(|env| -> jni::errors::Result<()> {
                let _ = env.throw(message);
                Ok(())
            })
            .into_outcome();
    }
}

impl From<MobilePlatform> for ClientKind {
    fn from(platform: MobilePlatform) -> Self {
        match platform {
            MobilePlatform::Ios => ClientKind::IosApp,
            MobilePlatform::Android => ClientKind::AndroidApp,
        }
    }
}

impl From<PushPlatform> for ProtocolPushPlatform {
    fn from(platform: PushPlatform) -> Self {
        match platform {
            PushPlatform::Apns => ProtocolPushPlatform::Apns,
            PushPlatform::Fcm => ProtocolPushPlatform::Fcm,
        }
    }
}

impl From<ProtocolAgentState> for AgentStateFfi {
    fn from(state: ProtocolAgentState) -> Self {
        match state {
            ProtocolAgentState::Idle => AgentStateFfi::Idle,
            ProtocolAgentState::Working => AgentStateFfi::Working,
            ProtocolAgentState::AwaitingInput => AgentStateFfi::AwaitingInput,
            ProtocolAgentState::Crashed => AgentStateFfi::Crashed,
        }
    }
}

impl From<ProtocolSessionSummary> for SessionSummaryFfi {
    fn from(summary: ProtocolSessionSummary) -> Self {
        Self {
            id: summary.id.to_string(),
            name: summary.name,
            command: summary.command,
            cwd: summary.cwd.display().to_string(),
            created_at: summary.created_at,
            last_activity: summary.last_activity,
            state: summary.state.into(),
            last_line: summary.last_line,
            model: summary.model,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex as StdMutex;

    #[derive(Clone, Debug, Eq, PartialEq)]
    enum SinkEvent {
        Initial(Vec<u8>),
        Output(Vec<u8>),
        AgentState(AgentStateFfi),
        Lag(u64),
        Exited(i32),
    }

    #[derive(Default)]
    struct RecordingSink {
        events: StdMutex<Vec<SinkEvent>>,
    }

    impl RecordingSink {
        fn events(&self) -> Vec<SinkEvent> {
            self.events.lock().expect("events lock poisoned").clone()
        }
    }

    impl ByteStreamSink for RecordingSink {
        fn on_initial_bytes(&self, bytes: Vec<u8>) {
            self.events
                .lock()
                .expect("events lock poisoned")
                .push(SinkEvent::Initial(bytes));
        }

        fn on_output(&self, bytes: Vec<u8>) {
            self.events
                .lock()
                .expect("events lock poisoned")
                .push(SinkEvent::Output(bytes));
        }

        fn on_agent_state(&self, state: AgentStateFfi) {
            self.events
                .lock()
                .expect("events lock poisoned")
                .push(SinkEvent::AgentState(state));
        }

        fn on_lag(&self, skipped_bytes: u64) {
            self.events
                .lock()
                .expect("events lock poisoned")
                .push(SinkEvent::Lag(skipped_bytes));
        }

        fn on_session_exited(&self, code: i32) {
            self.events
                .lock()
                .expect("events lock poisoned")
                .push(SinkEvent::Exited(code));
        }
    }

    #[test]
    fn extracts_json_from_qr_output() {
        let payload =
            "qr\n{\"node_id\":\"n\",\"addrs\":[],\"pair_token\":\"t\",\"expires_at\":1}\n";
        assert_eq!(
            extract_json_payload(payload).unwrap(),
            "{\"node_id\":\"n\",\"addrs\":[],\"pair_token\":\"t\",\"expires_at\":1}"
        );
    }

    #[test]
    fn rejects_invalid_device_secret_key() {
        let result = FieldworkClient::new(ClientConfig {
            device_name: "phone".to_string(),
            platform: MobilePlatform::Ios,
            device_secret_key: Some(vec![1, 2, 3]),
            paired_daemon: None,
        });

        assert!(matches!(result, Err(FieldworkError::InvalidConfig(_))));
    }

    #[test]
    fn stream_output_advances_mobile_reconnect_offset_without_decoding_bytes() {
        let session_id = SessionId::new();
        let attached = test_attached_session(session_id, 7);
        let sink = RecordingSink::default();
        let raw_bytes = vec![0x1b, b'[', b'3', b'1', b'm', 0xff, b'\r', b'\n'];

        let decision = attached
            .dispatch_stream_message(
                ServerToClientMsg::Output {
                    session_id,
                    seq: 42,
                    bytes: raw_bytes.clone(),
                },
                &sink,
            )
            .expect("dispatch output");

        assert_eq!(decision, StreamDecision::Continue);
        assert_eq!(attached.last_seen_seq(), 42);
        assert_eq!(sink.events(), vec![SinkEvent::Output(raw_bytes)]);
    }

    #[test]
    fn yes_head_10000_scale_stream_delivers_all_bytes_without_offset_drift() {
        let session_id = SessionId::new();
        let attached = test_attached_session(session_id, 0);
        let sink = RecordingSink::default();
        let mut expected_stream = Vec::with_capacity(20_000);
        let mut seq = 0;

        for _ in 0..100 {
            let mut chunk = Vec::with_capacity(200);
            for _ in 0..100 {
                chunk.extend_from_slice(b"y\n");
            }
            seq += chunk.len() as u64;
            expected_stream.extend_from_slice(&chunk);

            let decision = attached
                .dispatch_stream_message(
                    ServerToClientMsg::Output {
                        session_id,
                        seq,
                        bytes: chunk,
                    },
                    &sink,
                )
                .expect("dispatch output chunk");

            assert_eq!(decision, StreamDecision::Continue);
            assert_eq!(attached.last_seen_seq(), seq);
        }

        let mut actual_stream = Vec::with_capacity(expected_stream.len());
        for event in sink.events() {
            match event {
                SinkEvent::Output(bytes) => actual_stream.extend(bytes),
                other => panic!("unexpected sink event: {other:?}"),
            }
        }

        assert_eq!(actual_stream, expected_stream);
        assert_eq!(actual_stream.len(), 20_000);
        assert_eq!(attached.last_seen_seq(), 20_000);
    }

    #[test]
    fn lag_event_notifies_native_ui_and_stops_for_resync() {
        let session_id = SessionId::new();
        let attached = test_attached_session(session_id, 9);
        let sink = RecordingSink::default();

        let decision = attached
            .dispatch_stream_message(
                ServerToClientMsg::Lag {
                    session_id,
                    skipped_bytes: 3,
                },
                &sink,
            )
            .expect("dispatch lag");

        assert_eq!(decision, StreamDecision::StopForResync);
        assert_eq!(attached.last_seen_seq(), 9);
        assert_eq!(sink.events(), vec![SinkEvent::Lag(3)]);
    }

    fn test_attached_session(session_id: SessionId, seq: u64) -> AttachedSession {
        AttachedSession {
            session_id,
            send: tokio::sync::Mutex::new(None),
            recv: tokio::sync::Mutex::new(None),
            initial_bytes: tokio::sync::Mutex::new(None),
            initial_seq: seq,
            last_seen_seq: std::sync::atomic::AtomicU64::new(seq),
        }
    }
}

uniffi::setup_scaffolding!();
