[package]
name = "shelly-mobile-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Shelly Rust mobile core."

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
iroh.workspace = true
shelly-protocol = { path = "../protocol" }
reqwest.workspace = true
rustls.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { version = "1", default-features = false, features = ["io-util", "macros", "rt", "rt-multi-thread", "sync", "time"] }
uniffi = { workspace = true, features = ["cli"] }
webpki-roots.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
android_logger.workspace = true
jni.workspace = true
log.workspace = true
ndk-context.workspace = true

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
